### ISSUE TITLE
[yn-mask-number] min/value

### ISSUE THREAD

**Issue by Khokhlachov** [m-alx/yopsilon-mask#17]
Based on provided library explanation not clear flow for set  min/max value for number directive. 
Can you explain what is correct way to resolve it?

**Comment by m-alx** [comment]
Numeric format string takes the form `[prefix]{[format specifier][min integer digits]-[max integer digits].[min decimal digits]-[max decimal digits]}[postfix]`.

For example `{N1-6.1-2}`:
- `N` is a format specifier. Now only N (numeric) is supported. Can be skipped.
- `1-6` - minimum and maximum (from 1 to 6) number of integer digits.
- `1-2` - minimum and maximum (from 1 to 2) number of decimal digits.

Shortened notation is `{[min integer digits].[decimal digits]}`. Example: `{1.2}` where `1` is a minimum number of integer digits and 2 is a number of decimal digits (min=2 and max=2).

Also you can use chars `~` or `+` before prefix as a signum placeholder.
Example:  `~£{N1.2}`. If you need signum to be displayed for positive values too, use "+£{N1.2}" format.
