### ISSUE TITLE
Year issue?

### ISSUE THREAD

**Issue by Stan92** [m-alx/yopsilon-mask#19]
Hi,

I've noticed a strange behavior with the date mask (it also happens on the demo page).
If I enter 01/01/0000 the date comes as 01/01/2000 
In my case, it comes as 01/01/1900
Any help?

**Comment by m-alx** [comment]
Hi,

There was a bug in parser. Please check version 1.2.0. Now it sets full year (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#two_digit_years_map_to_1900_%E2%80%93_1999).

Also you can set min/max value for year:
```ts
import * as YN from 'yopsilon-mask';

YN.Mask.sectionTypes.find(st => st.datePart === 'yyyy').min = 1950;
```
or create custom section type:
```ts
public get settings(): YN.MaskSettings  {
      if (!this._settings) {
        this._settings = new YN.MaskSettings('_');
 
        this.settings.sectionTypes.push(
            { selectors: ['yyyy'], min: 1950, max: 2050, numeric: true, datePart: 'yyyy' }
          );
      }
      return this._settings;
  }
```
```html
<input yn-mask-date="mm/dd/yyyy" type="text" [yn-mask-settings]="settings" [(ngModel)]="dateValue" />
```
In this case autocorrector will fix entered string.

**Comment by Stan92** [comment]
Thanks. I'll make a try
