### ISSUE TITLE
The first number typed, after load the page, always dont write when i type a number sequence

### ISSUE THREAD

**Issue by EddyJunior** [m-alx/yopsilon-mask#2]

**Comment by m-alx** [comment]
Hi! Is this behaviour a demo page? In wich field?

**Comment by EddyJunior** [comment]
i was testing a angular application  and  it happened in input form of text type i was using template-drive (with ngModel). i was runnig in development mode

**Comment by EddyJunior** [comment]
but the only first digit typed dont write, after back to normal, of second to end

**Comment by m-alx** [comment]
I could not reproduce the problem. Please provide more information or source code of your component. Which browser is used?

**Comment by EddyJunior** [comment]
<form (submit)="onSubmit()">
  <input type="text" name="cpf" id="cpf" [(ngModel)]="cpf" yn-mask="NNN.NNN.NNN-NN">
</form>

**Comment by EddyJunior** [comment]
I tested in chrome, firefox and edge, all with same result.

steps to reproduce the little bug: 
1- i click on input (input in focus)
2- i type the first digit, but nothing happened
3- i type the my second digit and now show that second digit but like as my first digit

**Comment by EddyJunior** [comment]
<form (submit)="onSubmit()">
  <input type="text" name="cpf" id="cpf" [(ngModel)]="cpf" yn-mask="+1 NNNN NNNN-NN-NN">
</form>

**Comment by m-alx** [comment]
Such behavior occurs if the value of the model is undefined or null. I've uploaded a new version 0.5.2 of the 'yopsilon-mask' that fixes this problem. Please update package or set initial value of the model to an empty string.

**Comment by EddyJunior** [comment]
Now its works! thank so much
