### ISSUE TITLE
Currency format

### ISSUE THREAD

**Issue by andriyandrushko** [m-alx/yopsilon-mask#5]
Hello! Having trouble with formatting currency with negative values.
The current format is  £-12,000.22, can I change this to -£12,000.22? 
Thanks.

**Comment by m-alx** [comment]
OK, try version 1.1.2 with "~£{N1.2}" format. Char ~ is a placeholder for the signum.
If you need signum to be displayed for positive values too, use "+£{N1.2}" format.

**Comment by andriyandrushko** [comment]
Its works. Thank you!!!
